### ISSUE TITLE
Regex resources

### ISSUE THREAD

**Issue by lucymonie** [codingforeveryone/resources#3]
Please add your favourite **regex resources** below, or vote on those added by others.
- Resources should be added as comments
- Each resource you add should have its own comment so people can vote on each one separately
- Vote by giving a thumbs up to the comment
- It's helpful if you say whether the resource is a tutorial or a reference and what level (ie beginner, intermediate etc) 

Thanks!

**Comment by tomhuhges** [comment]
here's a load of fun regex crosswords - https://regexcrossword.com/
and an extra jumbo one - https://gregable.com/2015/12/regular-expression-crossword-puzzle.html

**Comment by tomhuhges** [comment]
this is a good tool for writing, testing and seeing useful snippets of regex - http://regexr.com/

**Comment by msachi** [comment]
online regex tester and debugger - helpful for breaking down a regex, identifying matched groups, testing substitutions etc. - https://regex101.com/

**Comment by msachi** [comment]
good tutorials of some of the concepts not covered well elsewhere, e.g. greedy & lazy quantifiers - http://javascript.info/tutorial/regular-expressions-javascript

**Comment by msachi** [comment]
a very thorough reference you may need when writing more sophisticated expressions - not limited to javascript - http://www.regular-expressions.info

**Comment by lucymonie** [comment]
RegexOne is a tutorial that starts simply and gets a little more complex. Good for beginners. Note: it doesn't deal with regex in the context of js, just raw regular expressions:
[http://regexone.com/](http://regexone.com/)

**Comment by powderham** [comment]
I would second regexone. I found it a great resource for learning regex originally..

**Comment by SavageWilliam** [comment]
A nice little "RegEx game"  to test your the learning -   http://regex.alf.nu/

**Comment by SavageWilliam** [comment]
I see @tomhuhges has also pointed out some RegEx games. Maybe we could make two **sections**? One for learning and one for applying/games?

**Comment by san00** [comment]
A really good online tutorial suited to different levels (beginner, intermediate & advanced) it has a full range of tutorials ranging from the fundamentals to more advanced regex expressions and also has language specific sections(JS, Ruby etc) http://www.rexegg.com/

**Comment by powderham** [comment]
http://www.regextester.com/

An environment in which to test, save and browse Regular Expressions
